// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_count from "./routes/api/count.ts";
import * as $api_search from "./routes/api/search.ts";
import * as $api_seed from "./routes/api/seed.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $populate from "./routes/populate.tsx";
import * as $DatabaseSeeder from "./islands/DatabaseSeeder.tsx";
import * as $PresentationDeck from "./islands/PresentationDeck.tsx";
import * as $Search from "./islands/Search.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/count.ts": $api_count,
    "./routes/api/search.ts": $api_search,
    "./routes/api/seed.ts": $api_seed,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/populate.tsx": $populate,
  },
  islands: {
    "./islands/DatabaseSeeder.tsx": $DatabaseSeeder,
    "./islands/PresentationDeck.tsx": $PresentationDeck,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
